### ISSUE TITLE
Weird version jump from 14.1.5 to 14.1.16

### ISSUE THREAD

**Issue by nrapel** [vaadin/platform#1123]
Is there a reason why we skipped 10 versions in between or it is just a typo?

**Comment by web-padawan** [comment]
This was a mistake that we unfortunately can't easily roll back because of [npm restrictions](https://docs.npmjs.com/cli/unpublish).

We considered the options and the best thing we can do is to keep this version as it it.
Sorry for the inconvenience. The [release notes](https://github.com/vaadin/platform/releases/tag/14.1.16) contain a mention, we'll make it more clear.

**Comment by nrapel** [comment]
Fair enough! :)
