### ISSUE TITLE
Duplicate key in package.json (Vaadin 16.0.0.beta2)

### ISSUE THREAD

**Issue by TGit911iger** [vaadin/platform#1340]
<img width="560" alt="Duplicate key" src="https://user-images.githubusercontent.com/9194576/82180024-f5f7ad00-98df-11ea-89f7-cd594f4954f9.png">

After generating for Vaadin 16.0.0.beta2 there are duplicate keys in package.json.

**Comment by ZheSun88** [comment]
Hi @TGit911iger ,

after `16.0.0.beta2` release, we have tested with our starter projects for validation. but we haven't found the issue you have mentioned here. you can take this as an reference. https://github.com/vaadin/skeleton-starter-flow/blob/master/package.json
probably there are some cache issues in your local project. 
Could you let me know the steps to reproduce this issue?

**Comment by web-padawan** [comment]
This issue is related to our `magi-cli` releasing tool and affects components that have `package.json`, which is the case for CRUD.

I confirmed this locally. The `"resolutions"` shouldn't technically break anything, but apparently it does in some development environments. We will release a new version with a fix.

**Comment by manolo** [comment]
@web-padawan I guess we can close this, right ?

**Comment by web-padawan** [comment]
This was fixed in `CrudFlow` 3.1.0 https://github.com/vaadin/vaadin-crud-flow/releases/tag/3.1.0
