### ISSUE TITLE
WIP: OSGi support for modular Vaadin views

### ISSUE THREAD

**Issue by mstahv** [vaadin/platform#1546]
As a developer
I want to package my Java based Vaadin views as OSGi bundles
So that I can add, remove and update individual views without restarting the whole OSGi based system.

## Acceptance criteria
- [ ] Example project build on top of OSGi, that demonstrates possibility to package views as separate bundles
- [ ] Case-specific criterion 1 (e.g. Closing browser removes temporary resources)
- [ ] Case-specific criterion 2
- [ ] Case-specific criterion 3
- [ ] Case-specific criterion 4

## General criteria
- [ ] APIs reviewed [here link to API review documentation, if any]
- [ ] Performance [here link to the requirement or tests, if any]
- [ ] UX/DX tests in Alpha [here link(s) to issue(s) with the description of UX/DX tests, if any]
- [ ] Design [here link to e.g. issue with design specification, a mockup, Figma specs] 

## Limitations
 * TS development mode is not supported at this point

#### **Do NOT use these just yet**
Under construction (would be used instead of User Value document - in the 2nd iteration of the template):  
- [ ] Documentation: [here link to the documentation]
- [ ] How to test? [here link to the GH issue or some external document with the test scenario]

**Comment by marcond** [comment]
Hello Matti

I've done this with Vaadin 7 for a project called LucidJ (https://github.com/neoautus/lucidj), where we used modular views heavily (not only modular code, but also modular runtime, with pluggable views/components).

I'm contemplating the possibility to update it, or migrate parts of it, to Vaadin 14 (or other suitable version).

Today, the most important question I have in mind is _what Vaadin version to target_. In just 3 years we saw Vaadin 8, then 10, then Flow/etc. While I had the desire to update LucidJ for new Vaadin versions, the "vaadin version" became a moving target, and company's priorities didn't followed it.

I could use some advise regarding this question. What would be a good Vaadin version to use as base for OSGi integration?

For your reference, you can find most of the integration work at:
https://github.com/neoautus/lucidj/tree/master/modules/vaadinui/src/org/lucidj/vaadinui

There are some other bits and pieces around on other modules, because the project is OSGi centric, but most of the interesting code is there. I liked that project a lot, and I think it would be nice to get the hands dirty again with Vaadin and OSGi :)

Have a great 2021 :)

**Comment by mstahv** [comment]
Hi @marcond, 

If you'd be building it today, Vaadin 8  is good choice. It has a solid OSGi support, still supported and migration from your Vaadin 7 project should be easy.

The long term choice should be Vaadin 20+, where we should be getting all the bits and pieces ready for OSGi.

BTW. Flow ~ the Vaadin Java framework in Vaadin 10+. Numbers growing with vast speed these days because we live in quarters ;-) But just wanted to underline that things aren't that complicated, there is basically Vaadin until version 8 and then the rewrite with the next gen framework and completely new components in V10+. All other releases are smaller than they appear.

**Comment by mstahv** [comment]
I'll merge this AC with #1547
