### ISSUE TITLE
AC: npm build compatibility for OSGi applications

### ISSUE THREAD

**Issue by mstahv** [vaadin/platform#1744]
As an OSGi developer
I want to create a Vaadin UI to my application as an OSGi bundle 
So that I can use the npm/webpack based build instead of using the deprecated bower/compatibility mode.

_With this feature we have a rudimentary support for OSGi development with modern Vaadin versions. The plan is to make development smoother and add more features and examples in the future releases._ 

## Acceptance criteria
- [ ] We have a separate VCDL licensed module for OSGi support
- [ ] There is an example that demonstrates how to deploy a Vaadin UI to an OSGi runtime with the http whiteboard specification 
- [ ] Documentation describes current limitations

## General criteria
- [ ] APIs reviewed (will be minimal, no actual API for end users 🤔) [here link to API review documentation, if any]
- [ ] ~~Performance~~ (No performance implications expected, developer experience expected to have issues: no development mode support at this point)
- [ ] UX/DX tests in Alpha [here link(s) to issue(s) with the description of UX/DX tests, if any]
   - Note: We should rely on external community members to test the feature as our own consultants have fairly limited OSGi experience.
- [ ] ~~Design~~(no UI features)

## Limitations
 - [ ] All development mode features are not supported, touching client-side resources can require a full build to see changes 
 - [ ] Push support don't need to be verified at this point

## Test plan

 - typical integration/regression tests to the OSGi project
 - Verifying quality with community members
   - approach known OSGi users directly
   - write a call for testers blog post describing the new OSGi functionality
 - Smoke tests in PiT phase for generic development workflow: Our own engineers (even without prior OSGi experience) must be able to check out our example project, run it and make simple changes to it.

**Comment by QNENet** [comment]
I am getting close to releasing a substantial OSGi/Karaf application based on V14 compatibility mode.

Attempting to build flow master to investigate the state of play with OSGi in V19, the build fails.

Using Intellij community version and setting up as outlined in Contributing.md the build fails because  of com.sun.beans.introspect.PropertyInfo problem, which does not seem to be solved as discussed in a few outstanding issues #8661 being the latest.

Advice on what settings are necessary to obtain a satisfactory build would be most appreciated.

And then, any pointers to tests and draft docs or code which might help in me following the V19 OSGi/Karaf  approach might result in me being able to provide feedback.

Thanks to Denis and Pekka I received some useful info on the flow Forum https://vaadin.com/forum/thread/18475014/osgi-status

**Comment by QNENet** [comment]
I have offered some suggestions in the flow repo  #9732
