### ISSUE TITLE
[BUG] flow-maven-plugin is part of vaadin-bom

### ISSUE THREAD

**Issue by pleku** [vaadin/platform#1902]
**Describe the bug**
For at least versions 14 and 18 the `com.vaadin » flow-maven-plugin` is part of `vaadin-bom` 

**To Reproduce**
Just check the dependencies list inside `vaadin-bom`

**Expected behavior**
It should not be part of any of those as it is not itself any public API that users need nor does even Maven work that way that you can manage plugin versions with BOMs.

**Comment by ZheSun88** [comment]
just did a quick check, the `flow-maven-plugin` is **not** coming from the [vaadin-bom](https://repo.maven.apache.org/maven2/com/vaadin/vaadin-bom/18.0.6/vaadin-bom-18.0.6.pom) directly, while it has been declared in the [vaadin-spring-bom](https://repo.maven.apache.org/maven2/com/vaadin/vaadin-spring-bom/18.0.6/vaadin-spring-bom-18.0.6.pom)

This dependency has been added there since our first release back to [vaadin-spring-bom:10.0.3](https://repo.maven.apache.org/maven2/com/vaadin/vaadin-spring-bom/10.0.3/vaadin-spring-bom-10.0.3.pom)

one of the examples for this usage in platform is the [vaadin-maven-plugin](https://github.com/vaadin/platform/blob/master/vaadin-maven-plugin/pom.xml#L24...L46), need to take a further look how it works there.

**Comment by ZheSun88** [comment]
we have decide:

remove the `flow-maven-plugin` dependency from `vaadin-spring-bom`
