### ISSUE TITLE
General question: JEE/Quarkus Support for Vaadin Fusion

### ISSUE THREAD

**Issue by ts-00** [vaadin/platform#2011]
I have 4 questions regarding Vaadin Fusion:

1. Does **Vaadin Fusion** work with Quarkus and JEE-Containers (for example, Wildfly) or is it only a framwork for Spring?

2. The core work of Vaadin Fusion is to generate Rest-Services and typescript code for java classes annotated with `@Endpoint`. Does Vaadin Fusion need Spring for generating this code? So if I use Quarkus instead, then Vaadin Fusion also includes Spring, am I right?

3. Does Vaading Fusion support communication also through WebSockets or SSE (Server Sent Events)?

3. Currently, I use https://github.com/vojtechhabarta/typescript-generator which is very great in generating typescript classes from java. However, I want to try out Vaadin Fusion to find out its benefits. Does Vaadin Fusion use https://github.com/vojtechhabarta/typescript-generator or http://www.jsweet.org/ ? If not, how does Vaadin Fusion transpiler compares to those typescript-generators? Why should I use Vaadin Fusion over https://github.com/vojtechhabarta/typescript-generator?

**Comment by Legioth** [comment]
Vaadin Fusion is a full-blown framework that uses Spring (Boot) as a runtime dependency for discovering implementing classes, dispatching requests, and accessing authentication information. The actual TS code generation doesn't directly depend on Spring but does instead use a combination of https://github.com/javaparser/javaparser and our custom Swagger integration.

If you're only interested in generating TS types based on Java types, then a standalone library might be easier to integrate. If you instead want to have a fully integrated opinionated full-stack framework, then Fusion might be suitable for your needs.

In addition to sending objects between the client and the server, Fusion also covers lots of other aspects such as:
* RPC abstraction for client-server communication that uses REST-like conventions and JSON as an implementation detail rather than as the primary representation.
* Form binding and validation based on metadata from Java types, including JSR 380 bean validation annotations
* Integration with the Vaadin design system that consists of a wide set of web components with a unified theming mechanism
* SPA bootstrapping and client-side routing for views
* Integration with webpack for bundling of client-side dependencies
* Service worker generation for automatic offline support

The TS generation in Fusion is quite similar to https://github.com/vojtechhabarta/typescript-generator, but it does also cover metadata such as JSR-380 bean validation annotations encountered on types that are sent from the client to the server. TS generation is only looking at type information and annotation but it doesn't look at the actual implementation in the way that e.g. JSweet does.

Support for other runtime environments than Spring is not at the top of the backlog but still under consideration. The same goes for support for pushing out messages from the server in addition to the typical request-response, although this can also be integrated separately using e.g. the SSE support in Spring.

**Comment by ts-00** [comment]
Thanks for the good answer.
