### ISSUE TITLE
Charts SVG export

### ISSUE THREAD

**Issue by rolfsmeds** [vaadin/platform#2101]
## Description
Server-side feature in Vaadin Charts for exporting a chart as SVG image data

## Use cases
As a developer
I want to export charts in the SVG format
So that I can convert it to other image types for downloading and embedding into reports

## Acceptance criteria
- [x] Server-side API for generating an SVG string based on the chart
- [x] Supports chart styling and configuration through Java API

## General criteria

- [x] UX/DX tests in Alpha:
* [test project with instructions in README](https://drive.google.com/file/d/1OkLGD1bKFiu087G4X5dcvXpte-Bp7Kh3/view) 
* [DX tests doc with instructions and findings](https://docs.google.com/document/d/1Op3JaJGDrtHniMlpLtiZ104CaWRHQwPL1Yoirc4_3CA/edit#heading=h.g1ttyink242t)

- [x] Documentation: 
* [vaadin.com/docs](https://vaadin.com/docs/latest/ds/components/charts/java-api/svg-generator)

- [x] How to test? 
1. Start with project from [start.vaadin.com](start.vaadin.com), [skeleton](https://github.com/vaadin/skeleton-starter-flow-spring) or use existing project with v21.
2. Add `vaadin-charts-flow-svg-generator` dependency 
3. Try the `SVGGenerator` with different charts and export options (tip: you can get some charts from the [demo](https://demo.vaadin.com/charts/))

- [x] Limitations: Mentioned in javadocs and docs:
* Node installation needed
* `vaadin-charts-flow-svg-generator` artifact is opt-in and needs to be added as a depedency
* Only considers styling from java API

**Comment by FollowSteph** [comment]
I don't know if this is possible but ideally it would be nice to be able to generate a png/jpg/gif for a specific size. Also if possible it would be great not to have to include a dependency like phantomJS like in Vaadin 8. Because if there's ever an exception in say a report generator then it can get quite complicated trying to close everything and so on. I understand that is is also targeted for version 21 but is it possible to export anything in version 14?

**Comment by alvarezguille** [comment]
You can use the Vaadin 21 version with Vaadin 14, there are [instructions for using newer charts version](https://vaadin.com/docs/latest/ds/components/charts/java-api/migrating-from-earlier-versions/#running-charts-9-in-v14) and also [instructions for using the SVGGenerator](https://vaadin.com/docs/latest/ds/components/charts/java-api/svg-generator) in the docs site.
You need to override `vaadin-charts-flow` version and add the matching `vaadin-charts-flow-svg-generator` dependency to your `pom.xml`:
```
<dependency>
    <groupId>com.vaadin</groupId>
    <artifactId>vaadin-charts-flow</artifactId>
    <version>21.0.0.alpha10</version>
</dependency>
<dependency>
    <groupId>com.vaadin</groupId>
    <artifactId>vaadin-charts-flow-svg-generator</artifactId>
    <version>21.0.0.alpha10</version>
</dependency>
```
Make sure that you have vaadin-prereleases maven repository defined in your `pom.xml` in order to get this dependencies (`21.0.0.alpha10` is currently the latest pre-release), the stable releases are expected for beginning of September.

With the new SVGGenerator you don't need to install PhantomJS like with Vaadin 8, but you need to have Node.js in both development and production servers. In order to avoid leaks like you mentioned now the `SVGGenerator` implements `AutoCloseable` and you should use it in a try with resources as suggested in docs:
```
try (SVGGenerator generator = new SVGGenerator()) {
    String svg = generator.generate(configuration);
} catch (IOException | InterruptedException ex) {
    // handle exceptions accordingly
}
```

You can use `ExportOptions` to configure the size of the SVG, and other libraries like Apache Batik to convert the svg to other formats.

**Comment by ssindelar** [comment]
Good to see that this finally happening. :)
