### ISSUE TITLE
Prepare for V11

### ISSUE THREAD

**Issue by ripla** [vaadin/platform#237]
- [x] Create a 10.0 branch
- [x] Protect it the same way as `master` in GitHub
- [x] Change current build confs to use that
- [x] Change create build confs to release 11.x from master

**Comment by SomeoneToIgnore** [comment]
Have also updated the release checklist with one tiny detail in `Build and stage Java parts` action description to mention the branch selection.

**Comment by SomeoneToIgnore** [comment]
Got a branch with updated versions: https://github.com/vaadin/platform/tree/kb/update-platform-verison

The branch fails with two errors:

* Currently we have an enforcer plugin that requires to specify all WebJars with versions AGAIN in the platform project, otherwise it fails. It is really weird since we have those dependencies fixed already in the component wrappers' projects.

* Even if I specify all transitive version, `vaadin-maven-plugin` project fails with compilation error, unable to see some `flow-server` classes, even if I add this dependency directly into the project.

**Comment by SomeoneToIgnore** [comment]
Stopping at this point, since don't know how to resolve both issues.

**Comment by ripla** [comment]
Implemented alternative approach with https://github.com/vaadin/platform/issues/243
