### ISSUE TITLE
Grid Inline Editing - Fails when equals and hashCode implemented

### ISSUE THREAD

**Issue by sfaust** [vaadin/platform#2666]
### Describe the bug

Inline editing cannot be completed once hashCode and equals have been implemented for the Row-Class. The Editor remains open after calling editor.save() (even for a valid row item) or editor.cancel()

### Expected-behavior

The Editor works correctly for all equals and hashCode implementations that fulfill the equals and hashCode contract. 

### Reproduction

Take the example from https://vaadin.com/docs/v14/ds/components/grid/#inline-editing
Add custom equals and hashCode (ie generated by IDE) to the Person.class
Inline-edit a Person
Change some property value ie the firstName
Cancel or Save 

### System Info

Win10, vaadin 14.8.0

**Comment by TatuLund** [comment]
> Add custom equals and hashCode (ie generated by IDE) to the Person.class

You probably have added hashCode and equals which uses all the fields of the bean. This will not work with Vaadin by design. Vaadin uses equals to find the item you edited (it needs to do this because of lazy loading nature and Vaadin is not doing double bookkeeping of items in order to conserve memory). In order this to work, the object identity needs to be invariant regarding edits. Say, if you have firstName property in Person object, changing the value of firstName should not change object identity. Hence if you define equals and hashCode in your object, you should only rely on some invariant property, such as id forexample. 

Case example, you can use super class like this as base for your entities.

`@MappedSuperclass
public abstract class AbstractEntity {

    @Id
    @GeneratedValue
    private Integer id;

    public Integer getId() {
        return id;
    }    public void setId(Integer id) {
        this.id = id;
    }

    @Override
    public int hashCode() {
        if (id != null) {
            return id.hashCode();
        }
        return super.hashCode();
    }

    @Override
    public boolean equals(Object obj) {
        if (!(obj instanceof AbstractEntity)) {
            return false; // null or other class
        }
        AbstractEntity other = (AbstractEntity) obj;

        if (id != null) {
            return id.equals(other.id);
        }
        return super.equals(other);
    }
}`

**Comment by sfaust** [comment]
Thanks your your explanations.

> You probably have added hashCode and equals which uses all the fields of the bean.

yes, that's what I did. 

> In order this to work, the object identity needs to be invariant regarding edits.

That may be quite hard to fulfill in some backend environments because of equals-implementations based on functional requirements. So we have to use dtos in this case, right?  

>In order this to work, the object identity needs to be invariant regarding edits.

I could not find that info in the docs. Would be cool to see it in a prominent place...
