### ISSUE TITLE
Multi-Select Combo Box (Web Component)

### ISSUE THREAD

**Issue by rolfsmeds** [vaadin/platform#2690]
## Description
A Combo Box component with multi-select support

## Use cases
As a developer
I want to use a compact, single-line multi-selection field in my form
So that I can avoid using a checkbox group that takes a lot more space

## Acceptance criteria
- [ ] Multiple items can be selected in the dropdown
- [ ] The dropdown indicates selected items with the regular selection checkmark
- [ ] Dropdown stays open after selection to aid selection of multiple items
- [ ] Each selected item is displayed in the field as a "chip" next to the filter field
- [ ] Item chips have a remove button that de-selects them and removes the chip
- [ ] The last item can also be de-selected with backspace in the field*
- [ ] If all chips don't fit in the field, all but the last chip are replaced with a single indicator that shows the number of overflowing chips (i.e. selected items - 1)
- [ ] Clicking the overflow chip opens the item dropdown
- [ ] Selection is appropriately announced by screen readers
- [ ] LTR mode support (remember to consider this in the arrow-left/right keyboard shortcuts as well)

\* To avoid inadvertent de-selection, pressing backspace _once_ in _empty_ filter field should _not_ remove the last chip immediately. Instead the last chip is highlighted (e.g. similarly to being focused) and removed on the next backspace. This highlighted state can also be reached by pressing arrow-left in the filter field. With the last chip highlighted, typing characters or pressing arrow-right moves focus back to the filter field.

## Features omitted from the initial version (but possibly added in the future)
- [ ] Wrapping mode, where the field grows vertically and chips wrap to multiple lines instead of collapsing into an overflow chip)
- [ ] Grouping selected items at the top of the dropdown

## General criteria
- [ ] APIs reviewed 
- [ ] Design 
- [ ] UX/DX tests in Alpha 
- [ ] Documentation: (new page to be added to Design System documentation) 
- [ ] How to test? 
- [ ] Limitations:

**Comment by jouni** [comment]
Here’s a quick sequence of states, how I see the component could work if we don't support multi-line:

![Multi select](https://user-images.githubusercontent.com/66382/152200381-bc28387c-a3a2-42b0-a426-bcc8a9304ef4.png)

Basically, chips are collapsed into an overflow item when there’s not enough space in the field. A minimum of roughly `4em` space should always be reserved for the text input area. Clicking the overflow chip would open up the overlay and show only those selected items that are collapsed into the overflow chip.

It might be better to move the overflow chip at the start of the field, so that backspace could always delete the last visible item. If only the overflow chip is visible, then I suppose backspace could either remove one selected item or all of them. Not sure which one would be more desired.

**Comment by jouni** [comment]
Alternatively to clicking the overflow chip and showing only the selected items, selected items could be grouped at the top of the overlay after it’s closed and reopened. Here’s an example of that kind of behavior: https://ej2.syncfusion.com/vue/demos/#/tailwind/multi-select/checkbox.html

**Comment by jouni** [comment]
Instead of only supporting a single-line field, but still supporting layouts that have restricted space for the field (for example grid headers), the field could expand in-place, when focused to show all selected items, without taking more space in the layout. An overlay of some sort. But that would likely be very complex to implement, so just offering that as a curiosity.

**Comment by rolfsmeds** [comment]
Looking at the designs above, I'm starting to wonder if the overflow chip should be somehow visually distinct from regular chips, since otherwise a quick glance at the field might trick the user into mistaking it for a regular selection chip and thus misjudge the current selection entirely.

Just some ideas off the top of my head here:
![image](https://user-images.githubusercontent.com/4611559/152307304-b9547417-4995-452f-8bd6-ed2638ad2267.png)

As for the backspace behavior with the overflow chip, the thought of backspace removing _one_ of the overflow items seems weird to me somehow, since you can't actually see which one that is, you just see the overflow count decreasing by one... so out of those two options, I think it would be better to remove _all_ items represented by the overflow.

Although, what about if we _always_ render at least one regular chip after the overflow? If there's not enough space for the entire chip, it would be truncated with ellipsis, but that way backspace would behave more intuitively predictably: always removing the rightmost item (and decrementing the overflow chip by 1 each time).

To illustrate, with a selection of `Option A, Option B, Option C, Option D, Option E`, backspacing would have the following effect step by step:
```
( 4+ ) (Option E)
( 3+ ) (Option D)
( 2+ ) (Option C)
(Option A) (Option B)
(Option A)
```

**Comment by jouni** [comment]
> Looking at the designs above, I'm starting to wonder if the overflow chip should be somehow visually distinct from regular chips

Lovely idea, thanks! I was also thinking about only showing a number, but that looked too much like a regular chip, but yeah, making it visually distinct in some other way makes things simple. No need to add any localization API for the "items" string.

**Comment by jouni** [comment]
> what about if we always render at least one regular chip after the overflow?

Yeah, that was what I was suggesting as an alternative as well ("It might be better to move the overflow chip at the start of the field, so that backspace could always delete the last visible item."). Would be great to build a quick prototype for this to test with.

**Comment by knoobie** [comment]
I like the design idea of the chips by Rolf! Little suggestion; would it be possible to have a `title` and aria-label or "tooltip" for the +3 chip that tells the user the names of the 3 items behind it?

**Comment by web-padawan** [comment]
>  would it be possible to have a title and aria-label or "tooltip" for the +3 chip 

That's how we handle in `vaadin-avatar-group`, so I suppose we could do the same.

**Comment by rolfsmeds** [comment]
With the overflow chip at the flex-start end of the field, if we went with the "stacked chips" design, it might make more sense for them to stack the other way, i.e. something like this
![image](https://user-images.githubusercontent.com/4611559/152344170-5a8603b4-71ea-46aa-9900-b9c3d50f26ec.png)
Not sure how to actually _implement_ that, since the eclipsed chips would need to be clipped somehow to be truly transparent due to both the field background and chips being semi-transparent (`--lumo-contrast-something`). I can't think of a `clip-path` based solution, and using an SVG mask would probably not work with a customizable `border-radius`. I suppose it might be doable with radial gradients or something, but my head hurts just thinking about it 😅

**Comment by jouni** [comment]
We can get quite close with something like this: 

```css

div {
display: inline-block;
width: 4px;
height: 26px;
border-left: 4px solid;
border-radius: 8px 0 0 8px;
margin-right: -4px;
}

```

![image](https://user-images.githubusercontent.com/66382/152403217-693a631f-c10d-45af-b4df-d33ead848ba5.jpeg)

**Comment by juuso-vaadin** [comment]
The original success criteria for overflow behaviour seems to be much simpler than the designs
>  If not all chips fit in the field, they are replaced with a single indicator that shows the number of selected items.

The overflow designs have good intention, but it seems to complicate things quite a bit.
Especially when combined with the requirement to remove items with backspace. Removing with backspace would also require moving the text cursor between any chips to be truly useful.

I'm worried that the increased number of different interactions will complicate the component too much. Current designs allows user to click on chip / overflow chip / dropdown and each have a different action. Would it be simpler if values are always added and removed via dropdown overlay similar to ComboBox? Additionally there could be a "clear" button similar to regular combo box to clear all values.

This component is still my favourite for the task:
https://ej2.syncfusion.com/vue/demos/#/tailwind/multi-select/checkbox.html

**Comment by juuso-vaadin** [comment]
For the use cases, I would imagine the component is **mainly** suited for selecting less than 10 items from a list of up to 50 items. Above those numbers it's better to use some type of list builder UI pattern.

The values seen in the designs are fairly simple, while in the real world the labels of the options are likely to be longer. This makes showing labels of multiple selected items in the field difficult. Maybe the behaviour could be so that if the field is allowed to grow, it will show item chips. If field has fixed size, it will change to indicate just the number of selected items once chips don't fit in field.

**Comment by McPringle** [comment]
The `MultiselectComboBox` from @gatanaso (see https://github.com/gatanaso/multiselect-combo-box-flow) is a very good reference. This is how it looks in a real-world application:

![2022-02-07 09_57_29-Event Administration](https://user-images.githubusercontent.com/1254039/152756542-bd6b2ede-8d74-4600-b5d3-f33542eb7191.png)

By default it grows vertically:

![2022-02-07 09_58_53-Event Administration](https://user-images.githubusercontent.com/1254039/152756805-d180f821-b6cb-4914-9523-a37a53715a82.png)

Searching in the values of the list box:

![2022-02-07 10_00_37-Event Administration](https://user-images.githubusercontent.com/1254039/152757076-0ae2c9aa-eed5-4ba1-92e3-9d497f9793f1.png)

There _can_ be more features, there _could_ be a fancier layout, but in my case (and I think in many others, too) there is no _need_ to. Start with a simple component - adding more features, styling, etc. can be done later incrementally.

_Maybe_ (depending on the license) it could be a solution to take the already working component (< Vaadin 21) from @gatanaso and just fix it for Vaadin 22+? IIRC, the Fusion version was already fixed for Vaadin 22.

**Comment by web-padawan** [comment]
>  it could be a solution to take the already working component (<= Vaadin 21) and just fix it for Vaadin 22+? 

Just to clarify, we will indeed use this component as a starting point, see https://github.com/vaadin/web-components/pull/3358
The purpose of this issue is to collect opinions on the feature design and to define acceptance criteria.

**Comment by jouni** [comment]
One of the restrictions/requirements we are working with is that the component should work in a "single line mode" by default, so that it won't expand vertically when more chips are added. One of the use cases for that would be a filter field in a data grid header. And some of our customers have also requirements where a field can’t change size inside a form.

Ideally we can eventually support both options (fixed height and auto height), but we’ll start with one for the first release.

**Comment by knoobie** [comment]
Question / Suggestion: Are the selected values inside the dropdown after re-opening at the top? see e.g. https://ej2.syncfusion.com/vue/demos/#/tailwind/multi-select/checkbox.html as example)

The idea comes from combo boxes with a lot of values / lazy loading where you probably can't see all (already selected) values on re-opening. Even a simple dropdown with "nationality" has over 100 values and if you have selected `German` and `Zambian` it would make removing `Zambian` kinda hard because you have to scroll to the end of the list.

**Comment by jouni** [comment]
That is one of the options we have been considering, yeah. That would probably be easier to understand that the alternative that I proposed, where by clicking the "overflow chip" would open the overlay with just the selected items.

**Comment by juuso-vaadin** [comment]
Reordering the selected to top should be a feature that can be opted-out. In some cases the order of items may give them a meaning and shuffling the items would hinder the UX.

**Comment by rolfsmeds** [comment]
I'd say the initial version should behave the same as the regular Combo Box, i.e. selected options are listed in the position they would normally have. We can later provide an opt-in feature for listing them in a (visually distinct) section at the top.

**Comment by esommars** [comment]
How about storing the selected values in the order thy where picked, and be able to drag and drop to reorder selected values?
Currently  https://github.com/gatanaso/multiselect-combo-box-flow is trashing the order after one rounds trip to DB as it is using HashMap for backing.

**Comment by jouni** [comment]
I feel that use case (where the order of the selection items matters) is outside the scope of this component, or at least our initial effort.

**Comment by knoobie** [comment]
> If all chips don't fit in the field, all but the last chip are replaced with a single indicator that shows the number of overflowing chips (i.e. selected items - 1)

Can this be enhanced with e.g. a title attribute that lists all selected values? That doesn't destroy the layouting but could help to quickly identify with mouse over what is selected without opening the drop-down and searching for the items (could be at position 1, 500 and 9899)

**Comment by web-padawan** [comment]
> Can this be enhanced with e.g. a title attribute that lists all selected values?

Yes, it probably makes sense. This is how the [original addon](https://github.com/gatanaso/multiselect-combo-box) works in "compact" mode.

**Comment by mheicke** [comment]
If somehow possible, a “select all” / “unselect all” functionality would be much appreciated. It’s especially helpful, for situations with many items

**Comment by web-padawan** [comment]
The clear button would make it possible to unselect all the items. We don't have a feature to select all though.
