### ISSUE TITLE
In Vaadin 7.2.6, we use icepush for servlet and javascript, Please suggest the alternative for vaadin 14.8.1

### ISSUE THREAD

**Issue by swatijain20** [vaadin/platform#2714]
### Describe the bug

In Vaadin 7.2.6, we use icepush for servlet and javascript API like below

ICEPush will be unavailable for Vaadin 14.8.1. But our vaadin guibase repo will not work without the below mentioned API’s used

ICEPush.setCodeJavascriptLocation
new JavascriptProvider
myJavascriptProvider.getJavaScript
myJavascriptProvider.getCodeName

Please sugegst alternate ways similar to above methods to enable upgrade to Vaadin 14.8.1

### Reproduction

In Vaadin 7.2.6, we use icepush for servlet and javascript API like below

ICEPush will be unavailable for Vaadin 14.8.1. But our vaadin guibase repo will not work without the below mentioned API’s used

ICEPush.setCodeJavascriptLocation
new JavascriptProvider
myJavascriptProvider.getJavaScript
myJavascriptProvider.getCodeName

Please sugegst alternate ways similar to above methods to enable upgrade to Vaadin 14.8.1

### System Info

vaadin old version: 7.2.6
vaadin current version: 14.8.1

**Comment by knoobie** [comment]
The addon states `This add-on is unnecessary since Vaadin 7.2. The built in push mechanism is more performant and more reliable and should be used instead of this add-on.`. You can remove it and use the default `@Push` mechanism Vaadin provides.

**Comment by TatuLund** [comment]
There is training video and example project on how the integrated Push feature in Vaadin 14 works here: https://vaadin.com/learn/training/v14-push

As stated by @knoobie , this feature has been part of Vaadin since Vaadin 7.2 (it had some issues, but reached good maturity at version 7.6). The usage pattern has been pretty much the same over the years.

You probably will face lot of questions during your migration process, I would recommend to reach for help in our Discord channel here: https://discord.com/channels/732335336448852018/774366825756229632
