### ISSUE TITLE
Dialog header and footer

### ISSUE THREAD

**Issue by rolfsmeds** [vaadin/platform#2785]
## Description
A built-in header and footer in Dialogs.

Most application dialogs have a header with a title and a footer with buttons. This feature will remove the need for implementing these separately in each project.

## Acceptance criteria
- [x] Static header and footer elements with scrollable content area in between
- [x] Arbitrary content can be placed in both
- [x] Footer styling consistent with that of [Confirm Dialog](https://vaadin.com/docs/latest/ds/components/confirm-dialog).
- [x] Header and footer hidden by default, enabled explicitly via API or implicitly by adding content to them
- [x] Built-in title text element in header, with dedicated API for setting its text (other header content rendered next to it)
- [x] Header functions as [drag-handle](https://vaadin.com/docs/latest/ds/components/dialog/#draggable) by default (edit: footer too)
- [x] Automatically remove Dialog's default padding when header and/or footer shown (and apply padding on content area instead, unless [explicitly disabled](https://vaadin.com/docs/latest/ds/components/dialog/#removing-the-padding))
- [x] Apply appropriate part names to header, title, content area and footer for styling
- [x] Consider making footer (and possibly header) non-static (part of scrolling content) on small viewports
- [ ] A11y: Ensure title is announced by screen readers when Dialog is opened (if title set)
- [x] A11y: Ensure focusable elements in header and footer are keyboard-accessible
- [ ] A11y: Ensure content area is scrollable by keyboard (or provide documentation for how to make the content area scrollable depending on the content)
- [ ] A11y: Ensure reasonable announcement even when header (and title) are not used (see https://github.com/vaadin/web-components/issues/3486).
- [ ] Make sure ConfirmDialog and CRUD (which use Dialog) are not broken by this, or refactor them to use the header and footer.

## General criteria
- [ ] APIs reviewed 
- [x] See ConfirmDialog
- [x] Performance 
- [x] UX/DX tests in Alpha 
- [x] Documentation: added to https://vaadin.com/docs/latest/ds/components/dialog
- [x] How to test? 
- [x] Limitations:

**Comment by knoobie** [comment]
Suggestion / Question: instead of adding the API to the dialog directly; could this be done inside a vaadin-window class which extends the dialog? Allowing people to use the low level "dialog" if they want to create a full custom solution and opt-in to the new (better / old way of things) dialog / window? Some people have probably created their custom solutions based on the dialog over the years (probably even extending the dialog with setHeader(String text) methods that could clash with method signature or overriding your new methods)

**Comment by rolfsmeds** [comment]
Well, by that logic we would soon have 100+ components instead of 40+, which is not a situation we want to be in (as each new component increases maintenance, release and documentation efforts significantly more than adding new features to existing ones, and also makes it harder for developers to figure out which component to use).

The intent is to make this as non-breaking as possible, in that the header and footer will be invisible by default, and only rendered if used (see criteria nr.4). I don't quite see how custom implementations for `setTitle`, `getFooter`/`getHeader` etc in subclasses of Dialog would be affected by the existence of corresponding methods on the base class – the subclass methods will simply override the base ones, which is why those developers would want anyway (until they refactor to use the built-in features). At worst they'll get a compiler warning about a missing `@Override` annotation, right?

Also we will probably ship this behind a feature flag at first to further decrease he risk of clashes.

**Comment by juuso-vaadin** [comment]
Optional X button in corner of dialog would be nice to have. There should be an easy way to add "expand to full screen" button. Maybe a dedicated slot within header for these icon buttons?

Is the footer intended to be simply a slot? Should there be some helpers for aligning the buttons (or button groups) to left / right?

**Comment by web-padawan** [comment]
> Is the footer intended to be simply a slot? 

I'd suggest to create a component for it, to be used also in `vaadin-confirm-dialog` and `vaadin-crud`. 
See https://github.com/vaadin/web-components/issues/858 where it is requested to make footers easier to theme.

**Comment by rolfsmeds** [comment]
Both header and footer will contain a slot for custom content, such as buttons, and while there are a lot of things we _could_ add as built-in features in those, we have decided not to include anything else (but the title) in this iteration.

Alignment is a good point though. You can of course simply slot in a layout aligned the way you want, but we could consider providing some kind of API for that into the header and footer itself. (I'm having a hard time imagining a nice clientside API for this, though... suggestions welcome!)

**Comment by knoobie** [comment]
Quick feedback for 23.1.0.alpha2 (Java side of things):

- replacing all my custom header, footer and scroller (thanks good finally gone) was as smooth as butter :heart: 
- having a semantic `<header>` and `<footer>` is totally awesome but should probably be documented because I, for example, removed / replaced my previously used `Header` and `Footer` with `FleyLayout` so that I don't have nested header and footer

Example using header/footer without title: 

![image](https://user-images.githubusercontent.com/3968629/163608102-cc162926-7989-4d64-ab39-474e922964a5.png)

 > A11y: Ensure title is announced by screen readers when Dialog is opened (if title set)
 
 Please allow for a hook for non-title dialogs like above :)
