### ISSUE TITLE
Make license checker independent of third party cookies

### ISSUE THREAD

**Issue by Artur-** [vaadin/platform#2938]
### Describe the bug

The license checker for commercial components relies on third party cookies. This does not work for Safari and also other browsers are working towards dropping third party cookies. Additionally if you have an ad blocker extension, it might block the used cookie.

### Expected-behavior

The license checker should work even if you do not allow cookies at all in your browser.

### Reproduction

Seen in any start.vaadin.com app with a Pro view + suitable browser setup

### System Info

-

**Comment by Avec112** [comment]
I would also like to remind you that some of us build and use Vaadin offline only. Since Vaadin 23 (or maybe earlier) there is bunch of annoying "Unable to validate the license for x" where x is any commercial component we are using. Also I do not thing the new Experimental feature "new licence checker" takes this in to account. As a paying customer with special (but also supported) needs I would very much like to not see any licence checking of any kind since this only generate noise on out side. Is it possible for Vaadin to tweak something that fits mine and others needs when using Vaadin offline?

**Comment by Avec112** [comment]
I was just informed about the new Licence Checker in 23.2. Looking forward to this change 
https://github.com/vaadin/platform/issues/2984
