### ISSUE TITLE
Multi-Select Combo Box (Flow Component)

### ISSUE THREAD

**Issue by yuriy-fix** [vaadin/platform#2961]
## Description
A Combo Box Flow component with multi-select support

## Use cases
As a developer
I want to use a compact, single-line multi-selection field in my form
So that I can avoid using a checkbox group that takes a lot more space

## Acceptance criteria
- [ ] Corresponding features of [Multi-Select Combo Box (Web Component)](https://github.com/vaadin/platform/issues/2690) are working.
- [ ] `MutliSelectComboBox` is implemented in `vaadin-combo-box-flow-parent` module.
- [ ] The new component should extend the `ComboBox`.
- [ ] Component implements [`MultiSelect`](https://github.com/vaadin/flow/blob/master/flow-data/src/main/java/com/vaadin/flow/data/selection/MultiSelect.java) interface.

  - [ ] The value of the component is represented as `Set<T>`.

- [ ] Should be possible to use component with `Binder` (corresponding tests should be added).

\* The initial / final PR should be requested from Goran. Inspiration for the implementation could be taken from [Goran's implementation](https://github.com/gatanaso/multiselect-combo-box-flow/blob/main/src/main/java/org/vaadin/gatanaso/MultiselectComboBox.java)

## General criteria
- [ ] APIs reviewed 
- [ ] Design 
- [ ] UX/DX tests in Alpha 
- [ ] Documentation: (new page to be added to Design System documentation) 
- [ ] How to test? 
- [ ] Limitations:

**Comment by TatuLund** [comment]
By default the popup is not closing when selecting items. This is a good default behavior since when you pick more than one, popup closing is annoying. I think majority of users wants to have it that way. 

Idea for MultiselectComboBox. I just did workaround for one of our customers using Gorans MultiselectComboBox, This customer how ever wanted to combo to close after item picked from popup. I was able to close it with JavaScript. I would say that it would be nice if we would have Java API to control the behavior.
