### ISSUE TITLE
Map: Support for different coordinate systems

### ISSUE THREAD

**Issue by rolfsmeds** [vaadin/platform#3106]
## Description
Add support for setting the projection / coordinate system used for getting and setting coordinates on the map. This includes built-in support for API for WGS84 (EPSG:3857 and 4326), which will be the new default, as well as API for defining custom projections.

## Use cases
As a developer
I want to use the same projection/coord.system with the Map component as is used elsewhere in our systems
So that I can use the Map component more easily without having to convert both ways each time

## Definitions

- View Projection: projection used by map data
- User Projection: projection used for coordinate getters/setters

## Acceptance criteria
- [ ] API for getting/setting the User Projection
- [ ] API for defining custom projections
- [ ] Provide built-in support for WGS84 projection
- [ ] API for "un-setting" the User Projection, so that the View Projection is used instead

## General criteria
- [ ] APIs reviewed 
- [ ] UX/DX tests in Alpha 
- [ ] Documentation: Update Map component docs to use new defaults, add section about projections
- [ ] How to test? 
- [ ] Limitations:

**Comment by sissbruecker** [comment]
If we decide to go with an approach to implement user projections on the Java-side, that could have a large impact on future efforts. One example would be supporting GeoJSON map features, either by loading it from a URL, or providing a JSON file. If we want to handle the coordinate conversion in Java, that also means we would have to implement loading / parsing GeoJSON in Java, and convert the coordinates contained within, before sending it to the client. On the other hand, if we were using the OpenLayers user projection feature, we could skip all of that and just hand the URL / JSON string to OpenLayers.

The main problem that we identified for the OpenLayers based solution was implementing custom projections from the Java side. After digging through the OpenLayers examples, it seems there might be an alternative to writing actual coordinate conversion logic in Javascript. OpenLayers has support for the [proj4js](https://github.com/proj4js/proj4js) Javascript library, which allows to define a custom projection in a text-based standard format called WKT (well known text). An example:

```js
import proj4 from 'proj4';
import {register} from 'ol/proj/proj4';

const epsg26986 = 'PROJCS["NAD83 / Massachusetts Mainland",GEOGCS["NAD83",DATUM["North_American_Datum_1983",SPHEROID["GRS 1980",6378137,298.257222101,AUTHORITY["EPSG","7019"]],AUTHORITY["EPSG","6269"]],PRIMEM["Greenwich",0,AUTHORITY["EPSG","8901"]],UNIT["degree",0.01745329251994328,AUTHORITY["EPSG","9122"]],AUTHORITY["EPSG","4269"]],UNIT["metre",1,AUTHORITY["EPSG","9001"]],PROJECTION["Lambert_Conformal_Conic_2SP"],PARAMETER["standard_parallel_1",42.68333333333333],PARAMETER["standard_parallel_2",41.71666666666667],PARAMETER["latitude_of_origin",41],PARAMETER["central_meridian",-71.5],PARAMETER["false_easting",200000],PARAMETER["false_northing",750000],AUTHORITY["EPSG","26986"],AXIS["X",EAST],AXIS["Y",NORTH]]';

proj4.defs('EPSG:26986', epsg26986);
// Register proj4js projections in OpenLayers
// which then allows using 'EPSG:26986' as view or user projection
register(proj4);
```

There are also web sites where you can look up the WKT for a specific projection, for example https://epsg.io/4326. So if we integrate `proj4js` into the Map component, then instead of having to write Javascript code that converts between projections, Java developers could just look up the WKT and define a custom projection using that. It would also be more convenient, as a WKT allows to convert between any two projections, while a custom function could only convert between two specific projections.

The `proj4js` project seems to be actively maintained and includes one main contributor from OpenLayers. Including the library with the component would increase the payload of the client-side bundle. Some basic testing around the `proj4js` payload in a production Vaadin app:

- Without `proj4js` (baseline): 461kB min+gzip
- With `proj4js` including predefined projections: 489kB min+gzip **(+27kB)**
- With `proj4js` excluding predefined projections: 473kB min+gzip **(+12kB)**

The last result excludes predefined projections, which we likely don't need. In order to achieve that we would have to modify the library somehow during the build. Not sure what would be the best way to achieve this, options could be to write a custom entry point / `index.js` file, or modify the webpack / Vite builds to replace the module containing the predefined projections with an empty file.

Another caveat of the OpenLayers based solution was that the user projection applies to all maps, at least per a page / view, which would still apply. Also we need to solve the problem on how to implement a (static?) API for this global setting, which eventually needs to run JS code on the client.
