### ISSUE TITLE
Vaadin trial

### ISSUE THREAD

**Issue by jawineh** [vaadin/platform#3732]
### Describe the bug

'C:\Program Files\Eclipse Adoptium\jdk-17.0.6.10-hotspot\bin\java.exe' '-agentlib:jdwp=transport=dt_socket,server=n,suspend=y,address=localhost:54848' .... AppData\Local\Temp\cp_90uc8u71kacz3qr83plx329lv1.argfile' 'com.example.application.Application'
Error: Could not find or load main class com.example.application.Application
Caused by: java.lang.ClassNotFoundException: com.example.application.Application'C:\Program Files\Eclipse Adoptium\jdk-17.0.6.10-hotspot\bin\java.exe' '-

### Expected-behavior

Expected to run the 'package com.example.application.views.main' but keep getting the above feedback. This is a free trial session but I'm unable to run it. In short the main class cannot be found or loaded.

### Reproduction

I don't know the solution.

### System Info

I am using VS code/java.

**Comment by oliveryasuna** [comment]
Do you have a repository we can look at?

**Comment by jouni** [comment]
Hi! Sorry to hear you’re having trouble getting started.

I don't really know what the problem is. I posted this issue in the Vaadin Discord chat as well (https://discord.com/channels/732335336448852018/774369063454638141/1072549807970865293), to see if someone there can help you out. Also, I suggest you ask further questions there, instead of opening issues here in the repository. You probably get faster replies that way.

**Comment by simasch** [comment]
How do you start the application?

Did you try to run it with Maven?

```
mvn spring-boot:run
```

**Comment by ZheSun88** [comment]
This issue has been inactive for over half a year, i will close this one. 
let us know if we can help further.
