### ISSUE TITLE
Faster Server Reloads in Flow

### ISSUE THREAD

**Issue by mshabarov** [vaadin/platform#4404]
## Description
As a Flow developer, the amount of time I have to wait before I see the effects of Java code changes in the browser is frustrating. These changes are often small, like fixing a typo on a component label, or switching a variable name. Still, even for small changes in a small project, it can take a couple of seconds before I see the changes reflected in the browser. In a large project, the refresh time can be much longer.

## Use cases
As a *developer*
I want to *have a faster server reloads in Flow*  
So that I can *see my Java changes in the browser immediately*  

## Acceptance criteria
- [x] Create a set of automated tests that run regularly to measure the refresh times of Flow apps of various sizes: plain non-Vaadin Spring-boot app, small Vaadin Spring-boot based app, large Vaadin Spring-boot based app. The tests are run regularly, and the measurements are stored. The measurements should be stored in a form that allows them to be easily used to compare the performance of different Vaadin versions and to detect regressions in the refresh times.
- [x] Focusing on small-sized Flow apps (a hello-world app),
   - [x] Investigate and document the factors contributing to the refresh time and the possible improvements of this refresh time.
   - [x] Estimate the effort required to implement the solution(s) identified.
   - [x] Involve the product team to decide if the solution can be implemented in the project’s timeframe.
- [x] Focusing on large-sized Flow apps,
   - [x] Investigate and document the factors contributing to the refresh time and the possible improvements of this refresh time.
   - [x] Estimate the effort required to implement the solution(s) identified.
   - [x] Involve the product team to decide if the solution can be implemented in the project’s timeframe.
- [x] Investigate https://github.com/vaadin/flow/issues/17428, this might contribute to the page reload overall time. 

NOTE: Non-Spring Boot and non-Maven apps are outside the scope of the project.

## General criteria

- [ ] APIs reviewed 

- [ ] Design 

- [ ] Performance 

- [ ] UX/DX tests in Alpha 

- [ ] Documentation: [Spring-boot DevTools tuning recomendations](https://vaadin.com/docs/latest/integrations/spring/configuration#configuring-spring-boot-development-tools)

- [ ] How to test? 

- [ ] Limitations: 

## Security
- [ ] Security implications have been taken into account (elaborate or link to product security requirement specification if there are implications)

**Comment by tltv** [comment]
List of merged pull requests contributing to faster reload time (build number inside square brackets):

- https://github.com/vaadin/flow/pull/17605 [116]
- https://github.com/vaadin/flow/pull/17591 [118]
- https://github.com/vaadin/flow/pull/17604 [119]
- https://github.com/vaadin/flow/pull/17621 [120]
- https://github.com/vaadin/flow/pull/17644) status: In progress

![image](https://github.com/vaadin/platform/assets/2182148/d0c86099-ca9e-4402-a198-ba29b49348f6)
Statistics showing starting point on the left side and results for each pull request. Showing results for Plain Spring boot Hello World, Vaadin Hello World and Large 1000 routes Vaadin application.

When comparing to build [112]: 

- Large Vaadin application reloads 2130 ms (**41.24 %**) faster 
- Hello World Vaadin reloads 1926 ms (**59.20 %**) faster
- also plain Spring Hello World reloads 923 ms (**61.21 %**) faster due to lower Spring Dev tools polling interval for file changes.

Documentation changes:
- https://github.com/vaadin/docs/pull/2770
  - Documented Spring Dev Tools properties: `spring.devtools.restart.poll-interval` and `spring.devtools.restart.quiet-period`
- https://github.com/vaadin/docs/pull/2803
  - Documented new `vaadin.devmode-caching` property

**Comment by tltv** [comment]
Some ideas for further research:
- Use parallel streams in class scanning code to improve scanning time (for read-only operations)
- Research indexing tools like Jandex to improve scanning time
  - Spring Indexing was tried out with 1000+ spring components but it did not improve scanning time. Also it only indexes Spring Components, not Vaadin Routes.
- Create a new plugin for IntelliJ IDEA Community edition (or find existing one that can be recommended) that supports [Spring Dev tools trigger file feature](https://docs.spring.io/spring-boot/docs/current/reference/html/using.html#using.devtools.restart.triggerfile) to reload instantly on demand/when all classes are compiled.
  - Commercial Enterprise version has already a build-in support for trigger file feature.
  - Motivation: IDEA is eager to do multiple restarts with default or lower polling-interval due to its habit to remove first and then add new classes.
