### ISSUE TITLE
Add slf4j version to the bom

### ISSUE THREAD

**Issue by Artur-** [vaadin/platform#49]

**Comment by Artur-** [comment]
Uh... that was 5 years ago. Probably to use the correct version? :)

**Comment by knoobie** [comment]
Good argument, I would have said the same thing after 5 years 😅 

I just came across this while trying to upgrade to 2.0.9 (because it finally contains a bom) and was checking where the oldish version came from and there I found this and got my wondering why.. I understand JNA because the whole app can break once it's not the correct version, but slf4j claims to be even binary compatible that I don't see any reason to have it here
