### ISSUE TITLE
PLEASE stop deleting important assets from releases [Software.Bill.Of.Materials.json]

### ISSUE THREAD

**Issue by dex-ds** [vaadin/platform#6639]
### Describe the bug

or provide them in every release to be sure your vaadin tool universe works as expected.
In my case the latest vaadin AppSecKit stops working.
Thank you

### Reproduction

![image](https://github.com/user-attachments/assets/4fe6a2d6-1b8a-4bde-abc0-2d460e19391d)

### System Info

AppSecKit 3.2.3

**Comment by dex-ds** [comment]
magical rebirth 👍
![image](https://github.com/user-attachments/assets/3d777af2-fca9-4178-b684-1e63b38f46fa)

I ask you to check which vaadin tools have dependencies to provided release assets. The question would also be why they are deleted at all.
It is not the first time that there are problems with the AppSecKit. It is extremely annoying to disrupt the development process because of such things.
Maybe @tamasmak  needs to check whether the AppSecKit can be freed from this dependency.
Thank you

**Comment by ZheSun88** [comment]
Hi, thanks for your patience. 
There is no process to delete the SBom artifacts from release note by us. But, in fact, there was a failure when running the older plugins, so that the build failed to upload. 

We have modifed the build now and will monitor the build for future releases. 

thanks again.
