### ISSUE TITLE
vaadin-maven-plugin 14.0-SNAPSHOT is not the same as flow-maven-plugin 2.0-SNAPSHOT

### ISSUE THREAD

**Issue by Artur-** [vaadin/platform#681]
When you test 14.0-SNAPSHOT, you must always separately change `vaadin-maven-plugin` to `flow-maven-plugin` `2.0-SNAPSHOT` to get the latest changes. It seems like 14.0-SNAPSHOT is not rebuilt when Flow is updated

**Comment by ZheSun88** [comment]
the problem with this issue is, platform snapshot is not released with every flow updates, but every commits in platform and nightly build. 

another thing is, with platform snapshot, it contains all the snapshot versions of our products. does it need to be updated with every flow update?

what i mean is, in platform `14.0-snapshot`, it contains `flow-maven-plugin` 2.0-snapshot. shouldn't the snapshot version catch the latest snapshot in the `vaadin-snapshot` repo?
