### ISSUE TITLE
v14rc6: Starter project 'Simple App' seems not to be best practice (not fully migrated to v14)

### ISSUE THREAD

**Issue by retomerz** [vaadin/platform#764]
The starter project 'Simple App' (HTML & Java), which could be download on the vaadin page for v14rc6 [1],
seems not to follow your best practice methods and or is not yet migrated to v14.

For example it contains a 'src/main/webapp/' directory.
And the MainLayout.java uses @JsModule("frontend://styles/shared-styles.js").
According to the migration guide [2] all the content of 'src/main/webapp/' should be moved to the 'frontend' directory.
And 'frontend://' prefix should be removed from @JsModule.

[1] https://vaadin.com/start/pre-release
[2] https://vaadin.com/tutorials/migrate-from-bower-to-npm-for-vaadin-14+

**Comment by Legioth** [comment]
The part about `/src/main/webapp` is actually an inaccuracy in the migration guide. It's actually `/src/main/webapp/frontend/` that should be moved to `/frontend`. The remaining file in the starter is an icon that should still be in `/src/main/webapp`. So that should be clarified in the migration guide instead of in the starter.

You are right about the `frontend://` protocol for the `@JsModule` annotation. On the other hand, the recently introduced `@CssImport` annotation should most likely be used instead of a JS Module import in this case. In either case, the current implementation is not correct.

**Comment by Legioth** [comment]
The tutorial is clarified in https://github.com/vaadin-learning-center/learning-content/pull/121.
The `frontend://` protocol is removed from the starter in https://github.com/vaadin/beverage-starter-flow/pull/403.

I'll close this issue since everything has been split up into individual parts.
