### ISSUE TITLE
Create an automatic end-to-end test for usage statistics collection

### ISSUE THREAD

**Issue by Legioth** [vaadin/platform#921]
Collection of usage statistics for individual Flow versions has been broken since npm mode was introduced and is fixed by https://github.com/vaadin/flow/pull/6706. This issues only affected various Flow features such as whether push or templates are used, but did not affect statistics about web components or Flow itself.

Automatic testing for the collection is slightly inconvenient from within the Flow project but it could potentially be done from the platform build. To test this functionality, you need to load a Flow view that also uses at least one Vaadin component, wait 10 seconds and then inspect the contents of `vaadin.statistics.basket` in localstorage. At least these entries should be present:
1. Flow (handled through special cases in the stats collector)
2. The Vaadin component (handled through generic logic in the stats collector)
3. The used Java version (fixed by vaadin/flow#6706)

**Comment by ZheSun88** [comment]
Testing under `production-mode` has been added via PR #931 , which it should not log anything in `vaadin.statistics.basket`, because the created production bundle will exclude the usage statistics code.

in order to test the info properly, we should add tests under `dev-mode`, which we don't have in platform project. So create another ticket to separate a module for `dev-mode` test.
